GET  http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InN0ZXZlQG1haWwuY29tIiwidXNlcm5hbWUiOiJzdGV2ZSIsImlzQXV0aG9yIjpmYWxzZSwiaWF0IjoxNzQzODUwODM2LCJleHAiOjE3NDM4NTA4OTZ9.m5roGJOYItwnqbRPnkgatK3FGLqn37fxsqIm2SGfByQ


###

POST  http://localhost:3000/login
Content-Type: application/json

{
    "email":"shay@mail.com",
    "password":"Shay@12345"
}

###

GET http://localhost:3000/token/refresh
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNSIsImVtYWlsIjoic3RldmVAbWFpbC5jb20iLCJ1c2VybmFtZSI6InN0ZXZlIiwiaXNBdXRob3IiOmZhbHNlLCJpYXQiOjE3NDM4MzUxODksImV4cCI6MTc0NDQzOTk4OX0.qE9peVLkg8UA4YQNHW9aJGzPPycLA-opw6RLGhBwXwM"
}

###
DELETE http://localhost:3000/logout
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNSIsImVtYWlsIjoic3RldmVAbWFpbC5jb20iLCJ1c2VybmFtZSI6InN0ZXZlIiwiaXNBdXRob3IiOmZhbHNlLCJpYXQiOjE3NDM4MzUxODksImV4cCI6MTc0NDQzOTk4OX0.qE9peVLkg8UA4YQNHW9aJGzPPycLA-opw6RLGhBwXwM"
}

###

POST http://localhost:3000/signup
Content-Type: application/json

{
    "username":"shay",
    "email":"shay@mail.com",
    "password":"Shay@12345",
    "isAuthor":"true"

}